apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: mq-git-repo
spec:
  params:
    - name: url
      value: 'https://github.com/<your github account>/cp4i-mq-tekton'
    - name: revision
      value: "master"
  type: git
