kind: Secret
apiVersion: v1
metadata:
  name: $MQ_CERT_SECRET
  namespace: $TARGET_NAMESPACE
data:
  tls.crt: >-
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURlakNDQW1JQ0NRQ1ZVZnM2USt4UzFEQU5CZ2txaGtpRzl3MEJBUXNGQURCL01Rc3dDUVlEVlFRR0V3SlYKVXpFTE1Ba0dBMVVFQ0F3Q1Rsa3hDekFKQmdOVkJBY01BazVaTVF3d0NnWURWUVFLREFOSlFrMHhEVEFMQmdOVgpCQXNNQkVOUVFWUXhGREFTQmdOVkJBTU1DMk52YlM1cFltMHVZMjl0TVNNd0lRWUpLb1pJaHZjTkFRa0JGaFJrCllXNXBaV3d1YjNKc1lXNUFhV0p0TG1OdmJUQWVGdzB5TURBMU1qVXhPREUxTVRsYUZ3MHlNVEExTWpVeE9ERTEKTVRsYU1IOHhDekFKQmdOVkJBWVRBbFZUTVFzd0NRWURWUVFJREFKT1dURUxNQWtHQTFVRUJ3d0NUbGt4RERBSwpCZ05WQkFvTUEwbENUVEVOTUFzR0ExVUVDd3dFUTFCQlZERVVNQklHQTFVRUF3d0xZMjl0TG1saWJTNWpiMjB4Ckl6QWhCZ2txaGtpRzl3MEJDUUVXRkdSaGJtbGxiQzV2Y214aGJrQnBZbTB1WTI5dE1JSUJJakFOQmdrcWhraUcKOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQW84OFh3L2NvRFhrcmUveHB2T2E4Uzh5RzZnQy9IR0I1NGpJaApyTU0vejBhRXFJWUtWVTZOVmE5cmZFYjk0TTA2b0swcXRhR2gyaklDeTV3VWlzUkoyNkxaODBGOEp4b3JldTN5CmVBaEwrZFk5elNhYzdSSTRydW1nYmUxdTBPR0FWSzR6aytnRG1CVTdabG1CSDdQUlZPL0V3NkF0QVIvSlpjL2sKWVlYQXJGM3BkYnI0VmZyNjVPdm9ZVW0rRDBVajZmMWgzL0E0VitPczlZWGp6UkJiMWpYVFZ6MzVPQ2VSc1NHYwpNVDNuSlF4ZzdJbzNUUmIxczhoWWdwZFRzSnFodWhBbUlqYjAzRmxldnZKSWR0anphcys5MWMwNmV5V084TFU2Ci9vYWlSUEZSZHZWc2VxSVM3ZFdKZVovbTUvMXM1RVRlYTZxQlV2Zm85V0I4TTVtdW13SURBUUFCTUEwR0NTcUcKU0liM0RRRUJDd1VBQTRJQkFRQnhVaHkwKzlmZmZKaE4xZ2Z2YzRYdnJmSkMyUEM0dDFjQ2xQQjZtZlZNNWt0dQpKLzI1NTMrTVcyNmRON1RBY09mblJvVjBYc3E2OXlFdVJtTm9iSWduUDd0TjlkVDN0RzUzaG9EdDhuNDVNNTlMCnVFMGpyemd3SWZJUFI5Z28xOExNZFBqTTI3MThlRk0ralBQUHRXcEJXSkFVenptUmxGUkFPcysyZFpGb3lVZEsKTHRMUUZZclJjanRtcW5mY0hHbFA5NExiWDdnU0JSVUllNmJRbVRMSkVaalJDNmo0MXFZTjFRaHo4UmhDalRJRAozTTl0Z2JGZHR6YUk2YXRUUjBjTDFibXV1ZERMNHorN3hESGlmWnRKTWlFeElNZGhzSjJURmlicFp2eDJNdURHCmtSWnJUVDR5ZU52cGdkeVVSRW9yN09PYlR5bFNqU0o1ZVVWT3ZIZncKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: >-
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRQ2p6eGZEOXlnTmVTdDcKL0dtODVyeEx6SWJxQUw4Y1lIbmlNaUdzd3ovUFJvU29oZ3BWVG8xVnIydDhSdjNnelRxZ3JTcTFvYUhhTWdMTApuQlNLeEVuYm90bnpRWHduR2l0NjdmSjRDRXY1MWozTkpwenRFaml1NmFCdDdXN1E0WUJVcmpPVDZBT1lGVHRtCldZRWZzOUZVNzhURG9DMEJIOGxseitSaGhjQ3NYZWwxdXZoVit2cms2K2hoU2I0UFJTUHAvV0hmOERoWDQ2ejEKaGVQTkVGdldOZE5YUGZrNEo1R3hJWnd4UGVjbERHRHNpamRORnZXenlGaUNsMU93bXFHNkVDWWlOdlRjV1Y2Kwo4a2gyMlBOcXo3M1Z6VHA3Slk3d3RUcitocUpFOFZGMjlXeDZvaEx0MVlsNW4rYm4vV3prUk41cnFvRlM5K2oxCllId3ptYTZiQWdNQkFBRUNnZ0VBV2xMeDdzdVUyVUVNR2pUSGRUTGhkd1pUQ2lyWk5tTjRNYUtrOE9kRWd4MkcKUG9xU25oRlBXNFQ3eHE0NmhUK0U2VjR5NDY0NVdlQWpySFBtMjlGNlRGS1N6VkE1ampJZThZek5HeVN3Q0JYNwpRK2pidE5sTVNoNW1xTmE0T1JOdXVNTEppKy91TTJqWnRRajdheWl5NzV1NktvaGk2SERIazQwN2lBN0JmQWoyClhjOTlGQnVRVlVrMFRvRWFSVU5mTDlWSUtEYmlyS1RDOS9TVnBuZ0x5VWYxU1ZadksxY3RjbDJEME4xc1NMdTEKa3NHSS9rblZDcXFuYlZGd0liWWpwUHI3ejZja2F5bnhhYmREV2cybGdVa0U5T1JId0JXZU9HNjZ3UFM4RjhXQQo4T0hNVWFhSk5rNGpjUWY1TktUVzNCNnJZbnk0V0g5NUVlTGwzVFZXbVFLQmdRRFpLdld6U2dQeFR3M0hnaTh5ClNlY29mVjhGMkl5clpIMjYrcFRVcFArbXFYbzJzLzJweEFlWUZLQkVuNk5oOHFhRmlzazRydzUwTFFTdVlwRTQKdUlWWEtLdFpyVWhMalZjY1U1ZGtXOGh4UE1lOVFmd015UEZuRU5CcmdKaXBYYUI1VW05UzBJWDhwa2M4azhZZgpTc3pIdVI5NlFtODB3R3dJMXk0OUdQUlRqd0tCZ1FEQkdaWWFyZVdtV2dmNFpReEY0K3Fnc0dPc3FEdjNFeUFEClkxUnNuOXAwbWJJdHlHVTQ2QWE0dDNmQmhFTXZrZEpLdWkxd3lXa2xSN2V2UVJSWFgrUjFLOUxsR3VnK0crd2wKVGsvejMyL3J4dE5iczVTczRCUDkxajBLMUx3OXZtaGRvR25QMHIwRXlHU1J4cDd1Rld3RGp0MnN3RkphSk9Zdgo4bHdaOTl4K05RS0JnUUN6RnloMGFJK0R5dXZVSWRvR0lNZ09yZ1ZVN3RaaTZZWitVZk8yd1ROTEgreDNmRXV1CldzamdjL0lQWlk3NVVZQmVGS3dJb09UTWpldVVYQmppcTlqYW5lRmhIUFBIeXBHUi9LV1d6OUluQURiQUx0QkwKUXROQmFhNVhXVCtNUEhnQVZTa1ZKSDI2Y3UzQVdTVkQzUTJ2ajAwVUtBRkpnWDRXZEUzZmVOclVwUUtCZ0ZWKwpWbzhKWHh2LzBIZVJoWldNQzEySnV4ZStoSTRuMFl5dWRicUNLOTVrRGhkbkdpblAwT29Ia09ZRkFSb1duZHlvCkFXWm1SajlUT1doR2tCTC9TYzcyMEREUGNQUE91UWJyWFVyRUtuRmhYa0xEaDVmaXZmY3MyMm5vTmsrLzljVSsKT0pyaTJ2MDdIQXZPdko3OHJRNEdPdTg1Vnp6Q0NZaEE3Yll4bjFYaEFvR0JBTHFWNkk5WGhjcWJlK3VycnFlaAo1YVc5NDY3UmdaS1JnS0MxblN2elVmZys4S1cvYTVId1gwQkZIeFZlN29DNjlHejhiZXJMTStobW5QM3RWYW1VCmZWTWR3d2xmM0Q2dGRJYVZNRnNlR1l6Zk9ORXNCR1JMWmY5Sk80cWx4dUNERHo2TDhtUVVuM21kYkN4SVRRNG8KQk9kMmRLL3ovYzFVdmpFVEVxUks3RkJLCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
  app.crt: >-
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURlakNDQW1JQ0NRQ0tscGJTbitnSXFEQU5CZ2txaGtpRzl3MEJBUXNGQURCL01Rc3dDUVlEVlFRR0V3SlYKVXpFTE1Ba0dBMVVFQ0F3Q1Rsa3hDekFKQmdOVkJBY01BazVaTVF3d0NnWURWUVFLREFOSlFrMHhEVEFMQmdOVgpCQXNNQkVOUVFWUXhGREFTQmdOVkJBTU1DMk52YlM1cFltMHVZMjl0TVNNd0lRWUpLb1pJaHZjTkFRa0JGaFJrCllXNXBaV3d1YjNKc1lXNUFhV0p0TG1OdmJUQWVGdzB5TURBMU1qVXhPREUyTVRGYUZ3MHlNVEExTWpVeE9ERTIKTVRGYU1IOHhDekFKQmdOVkJBWVRBbFZUTVFzd0NRWURWUVFJREFKT1dURUxNQWtHQTFVRUJ3d0NUbGt4RERBSwpCZ05WQkFvTUEwbENUVEVOTUFzR0ExVUVDd3dFUTFCQlZERVVNQklHQTFVRUF3d0xZMjl0TG1saWJTNWpiMjB4Ckl6QWhCZ2txaGtpRzl3MEJDUUVXRkdSaGJtbGxiQzV2Y214aGJrQnBZbTB1WTI5dE1JSUJJakFOQmdrcWhraUcKOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQTRkVFhUbUFKK1krOThyV0lkNEdRSGRxdkxqUlFZSFhDWTRlMgpGUHVYOFF1VlJUUlU2czl3elZNVXFKaEluSDg3VEt5QW90MFppYUVNdHF0Y21pd2EwWjFXVmN0Ni9EY08rajQzCnU4ZXlFMG9EQXhPREFQbEdOWjhJR1haV1h1ZGYwOFRBVWRKZHlkeUwyL2Y0NmpGNktjYTRpNUVEVW81ZUFNUlYKeWl4RWY3dXUwUm05aWJ1YkFyRXFkd0cwdVhwYWNwcjBvYkw0MTEvLzV6Zm1Ba0UwS3pQRmhVTlV2ZGVidFk2cQplQ09SMzRyaTdXZ0hVSm5ucVRzVUhjcWgxRFBUdzBYeVRHOS9CdFVRN21ZemNvRitKVEpFaW1US0RtZkZteXlNCkFhT3lVbWZ2WVBBc3l1UGZHeTd2WGlrby9OOTJFWU9hQnZOOTcxS013dEg1MGw2UmV3SURBUUFCTUEwR0NTcUcKU0liM0RRRUJDd1VBQTRJQkFRQXBwSkYzZ2RIejg4MzZBKzIyVnFVNWRNR1RMeUxoVTdLYjJ6Z2tsaERaZmd1awozSWtObE5SUHUvTHJGeHNKcGkvaFdnU1pnUlNtckJsWG5uUVc1KzFsV1JTM04yOHMxYXo5VEl1QUpmbWlicWhVCnVERE0xZTgvSi9kdVdkZmM4b05rNzcycC9xOVlwVDJLdW5LcHhjR2NWMkxHcmZQTmVLSllHVDFEQmxkd09KaUgKcDFYdWxoODZxelIvWHB5N0VvclZEM2VEZnMyUmZSR2JnT2FPN3NLK3hTTFU0RWd2QWVwU0NiZmExdDNscTNyRAplWUV4RkIzS1VyRm1hRmR2YmZqL2laOXNLazQ1eis3SlpuVE5VdDlFTkZLK3FaUnpnUGxqaHpmOUJxV2tjS3dzCkdhVnptODNmYVk1QW1SclVCcnp3bU9nNEt5MGZEbUp4ekRrWVl3YTcKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
type: kubernetes.io/tls
---
apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: $QM_POD_NAME
  namespace: $TARGET_NAMESPACE
spec:
  version: 9.2.2.0-r1
  license:
    accept: true
    license: L-RJON-BXUPZ2
    use: NonProduction
  pki:
    keys:
      - name: default
        secret:
          secretName: $MQ_CERT_SECRET
          items:
            - tls.key
            - tls.crt
    trust:
      - name: app
        secret:
          secretName: $MQ_CERT_SECRET
          items:
            - app.crt
  template:
    pod:
      containers:
        - env:
            - name: MQSNOAUT
              value: 'yes'
          name: qmgr
  web:
    enabled: true
  queueManager:
    name: $QM_NAME
    mqsc:
      - configMap:
          items:
            - config.mqsc
          name: $MQSC_CM_NAME
    storage:
      queueManager:
        type: ephemeral
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: $ROUTE_NAME
  namespace: $TARGET_NAMESPACE
spec:
  host: $SVRCONN_SNI
  to:
    kind: Service
    name: $QM_POD_NAME-ibm-mq
  port:
    targetPort: 1414
  tls:
    termination: passthrough
