kind: ConfigMap
apiVersion: v1
metadata:
  name: mq00d-uniform-cluster-mqsc-1
  namespace: cp4i-mq
data:
  disablesecurity.mqsc: |-
    *##########################################################################
    * Configuration for all queue managers
    *##########################################################################
    define QL(APPQ) cluster(UNICLUS00) defbind(notfixed) clwluseq(any) maxdepth(99999999) replace
    define QL(APPQ2) cluster(UNICLUS00) defbind(notfixed) clwluseq(any) maxdepth(99999999) replace
    define channel(TO_UNICLUS_mq00d) chltype(clusrcvr) trptype(tcp) conname('mq00d-ibm-mq(1414)') cluster(UNICLUS00) replace
    define channel(TO_UNICLUS_mq00b) chltype(CLUSSDR) trptype(tcp) conname('mq00b-ibm-mq(1414)') cluster(UNICLUS00) replace
    define channel(TO_UNICLUS_mq00a) chltype(CLUSSDR) trptype(tcp) conname('mq00a-ibm-mq(1414)') cluster(UNICLUS00) replace
    define channel(TO_UNICLUS_mq00c) chltype(CLUSSDR) trptype(tcp) conname('mq00c-ibm-mq(1414)') cluster(UNICLUS00) replace
    DEFINE CHANNEL(mq00chld) CHLTYPE(SVRCONN) TRPTYPE(TCP) SSLCAUTH(OPTIONAL) SSLCIPH('ANY_TLS12_OR_HIGHER') replace
    DEFINE CHANNEL(TO_UNICLUS00) CHLTYPE(SVRCONN) TRPTYPE(TCP) SSLCAUTH(OPTIONAL) SSLCIPH('ANY_TLS12_OR_HIGHER') replace
    ALTER QMGR CHLAUTH(DISABLED)
    ALTER AUTHINFO('SYSTEM.DEFAULT.AUTHINFO.IDPWOS') AUTHTYPE(IDPWOS) ADOPTCTX(YES) CHCKCLNT(OPTIONAL) CHCKLOCL(OPTIONAL) AUTHENMD(OS)
    REFRESH SECURITY TYPE(CONNAUTH)
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: mq00d-uniform-cluster-ini-1
  namespace: cp4i-mq
data:
  uniformcluster.ini: |-
    TuningParameters:
       UniformClusterName=UNICLUS00
---
apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: mq00d
spec:
  version: 9.2.0.0-r2
  license:
    accept: true
    license: L-RJON-BN7PN3
    use: "NonProduction"
  pki:
    keys:
    - name: default
      secret:
        secretName: mq00-uniform-cluster-cert
        items:
          - tls.key
          - tls.crt
  web:
    enabled: true
  securityContext:
    supplementalGroups: [99]
  queueManager:
    availability:
      type: SingleInstance
    storage:
      persistedData:
        enabled: true
        class: ibmc-file-gold-gid
      queueManager:
        enabled: true
        class: ibmc-file-gold-gid
      recoveryLogs:
        enabled: true
        class: ibmc-file-gold-gid
    securityContext:
      supplementalGroups: [99]
    mqsc:
      - configMap:
          name: mq00d-uniform-cluster-mqsc-1
          items:
            - disablesecurity.mqsc
    ini:
      - configMap:
          name: mq00d-uniform-cluster-ini-1
          items:
            - uniformcluster.ini
  template:
    pod:
      containers:
        - env:
            - name: MQSNOAUT
              value: 'yes'
          name: qmgr
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: mq-traffic-mq-mq00d-ibm-mq-qm
  namespace: cp4i-mq
spec:
  host: mq00chld.chl.mq.ibm.com
  to:
    kind: Service
    name: mq00d-ibm-mq
  port:
    targetPort: 1414
  tls:
    termination: passthrough
  wildcardPolicy: None
---
